[package]
name = "wzip"
version = "1.0.0"
authors = ["Benedikt Spies"]
edition = "2018"

[dependencies]
flate2 = "1.0"
clap = "2.33.0"
tree_magic = "0.2.1"

[dev-dependencies]
file_diff = "1.0"

[[bin]]
name = "wzip"
path = "src/main.rs"

[profile.release]
lto = true